### ISSUE TITLE
Env var GITHUB_ACTION is not defined. Maybe try to set it if you are running the script manually.

### ISSUE THREAD

**Issue by bluelovers** [Ilshidur/action-discord#39] opened 2020-08-04 04:30 UTC
https://github.com/bluelovers/ws-segment/runs/943356195?check_suite_focus=true

**Comment by foosel** [comment] 2020-08-04 06:31
Seeing the same, probably caused by https://github.com/actions/runner/issues/635

**Comment by Ilshidur** [comment] 2020-08-04 06:41
Looks Github an issue on GitHub's end. I'll deploy a quick fix until they solve this issue.

**Comment by Ilshidur** [comment] 2020-08-04 06:51
**Fix is pushed.**

To fix your pipeline, check sure the version you use is at least `Ilshidur/actions-discord@fbd91a9`. [Here's a link to the commits list for clearance.](https://github.com/Ilshidur/action-discord/commits/master)
You should be fine if your Action is not locked on a certain version SHA-1 (e.g.: `Ilshidur/actions-discord@master`).

I'll have a close look on GitHub's behavior concerning this issue. Thank you.

**Comment by foosel** [comment] 2020-08-04 07:32
@Ilshidur Lovely, thank you for the quick turn around! I was just about to disable discord notifications on my project until Github fixes this on their end, but you just made that unnecessary. Thank you for your awesome work!

**Comment by Ilshidur** [comment] 2020-08-04 07:37
Thank **you** for your the link your provided. It made it clearly quicker to fix !

I'll be closing this issue. Feel free to comment below in case anything goes wrong again.

**Closed by Ilshidur** 2020-08-04 07:37 UTC
Labels: bug
